# Generated by Django 5.2.6 on 2025-09-17 04:52

import django_profileboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profileboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasequery',
            name='params',
            field=models.JSONField(default=dict, encoder=django_profileboard.models.SafeJSONEncoder),
        ),
        migrations.AlterField(
            model_name='databasequery',
            name='stack_trace',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
